# Generated by Django 2.2.2 on 2019-06-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190612_2250'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Course',
            field=models.ManyToManyField(to='course.Course'),
        ),
    ]
