# Generated by Django 2.2.2 on 2019-07-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190630_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
